'use strict';

const CREATE_PROJECT = 'CREATE_PROJECT';
const OPEN_PROJECT = 'OPEN_PROJECT';

const UPDATE_PROJECT = 'UPDATE_PROJECT';
const UPDATE_PROJECT_HEADING = 'UPDATE_PROJECT_HEADING';
const UPDATE_PROJECT_TEXT = 'UPDATE_PROJECT_TEXT';
const UPDATE_PROJECT_LINK = 'UPDATE_PROJECT_LINK';
const UPDATE_PROJECT_LOGO = 'UPDATE_PROJECT_LOGO';
const UPDATE_PROJECT_IMAGE = 'UPDATE_PROJECT_IMAGE';
const UPDATE_PROJECT_BACKGROUND = 'UPDATE_PROJECT_BACKGROUND';

const PROJECT_PART_HEADING = 'heading';
const PROJECT_PART_TEXT = 'text';
const PROJECT_PART_LINK = 'link';
const PROJECT_PART_LOGO = 'logo';
const PROJECT_PART_IMAGE = 'image';
const PROJECT_PART_BACKGROUND = 'background';

module.exports = {
    CREATE_PROJECT,
    OPEN_PROJECT,
    UPDATE_PROJECT,
    UPDATE_PROJECT_HEADING,
    UPDATE_PROJECT_TEXT,
    UPDATE_PROJECT_LINK,
    UPDATE_PROJECT_LOGO,
    UPDATE_PROJECT_IMAGE,
    UPDATE_PROJECT_BACKGROUND,
    PROJECT_PART_HEADING,
    PROJECT_PART_TEXT,
    PROJECT_PART_LINK,
    PROJECT_PART_LOGO,
    PROJECT_PART_IMAGE,
    PROJECT_PART_BACKGROUND
};
